"""Clean migration for batch updates

Revision ID: 17502ad9cb2c
Revises: 
Create Date: 2025-06-26 23:51:15.142296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17502ad9cb2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('large_sensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('large_unsensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('small_sensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('small_unsensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thumb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('thumb')
        batch_op.drop_column('small_unsensorized')
        batch_op.drop_column('small_sensorized')
        batch_op.drop_column('large_unsensorized')
        batch_op.drop_column('large_sensorized')

    # ### end Alembic commands ###
