"""Add mmd_id column to batch

Revision ID: 4e0a5bd7d086
Revises: 17502ad9cb2c
Create Date: 2025-06-30 17:44:40.592197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0a5bd7d086'
down_revision = '17502ad9cb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_batch')
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mmd_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_mmd_id', 'mmd', ['mmd_id'], ['id'])
        batch_op.drop_column('mmd_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mmd_version', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mmd_id')

    op.create_table('_alembic_tmp_batch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('technician_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mmd_version', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    # ### end Alembic commands ###
