"""Updated batch schema

Revision ID: 7436a1f47aa5
Revises: 
Create Date: 2025-05-10 22:29:32.668734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7436a1f47aa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_name', sa.String(length=50), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('mmd_version', sa.String(length=10), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('mmd_version')
        batch_op.drop_column('technician_name')

    # ### end Alembic commands ###
