"""Add BatchFailure model and batch_failures relationship

Revision ID: a7bc4fc7af71
Revises: 
Create Date: 2025-07-18 08:30:33.938806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bc4fc7af71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_failure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('large_sensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('large_unsensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('small_sensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('small_unsensorized', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thumb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_historical', sa.Boolean(), nullable=True))
        batch_op.alter_column('batch_number',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('technician_name',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('mmd_id',
               existing_type=sa.TEXT(length=10),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_foreign_key(None, 'mmd', ['mmd_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('mmd_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(length=10),
               nullable=False)
        batch_op.alter_column('technician_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=False)
        batch_op.alter_column('batch_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=False)
        batch_op.drop_column('is_historical')
        batch_op.drop_column('thumb')
        batch_op.drop_column('small_unsensorized')
        batch_op.drop_column('small_sensorized')
        batch_op.drop_column('large_unsensorized')
        batch_op.drop_column('large_sensorized')

    op.drop_table('batch_failure')
    # ### end Alembic commands ###
